teste = "excelsior"

print(teste.isalpha())  
print(teste.isdigit())  
print(teste.isalnum())  
print(teste.islower())  
print(teste.isupper())  
print(teste.isspace())  
print(teste.capitalize())  
print(teste.title())  
print(teste.lower())  
print(teste.upper())  
print(teste.strip())  
print(teste.replace('e', 'b'))  
print(teste.split())  
print(teste.join(['a', 'b']))  
print(teste.count('a'))  
print(teste.startswith('a'))  
print(teste.endswith('a'))  
print(teste.splitlines())  
print(teste.partition('a'))  
print(teste.rpartition('a'))  
print(teste.zfill(5))  
print(teste.format_map({}))  
print(teste.removesuffix('a'))  
print(teste.isnumeric())  